#ifndef V_INTERFACE_H_
#define V_INTERFACE_H_

#define FINTERFACE(X) ANSI_BOLD_HI_PURPLE X ANSI_COLOR_RESET
#define FADDR(X)      ANSI_BOLD_HI_BLUE X ANSI_COLOR_RESET
#define FDATA(X)      ANSI_BOLD_HI_YELLOW X ANSI_COLOR_RESET


#endif /* V_INTERFACE_H_ */
